env:
  global:
    - CC_TEST_REPORTER_ID=23e59016c49019de978d1a6cc52bf219c29ef17497c3fd9b052ab4c05713aab2
language: node_js
node_js:
  - "8"
  - "6"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules # NPM packages
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip2 install yapf;
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip2 install yapf;
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter;
    else
      echo Error:TRAVIS_OS_NAME && exit 1;
    fi
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yapf --version
  - npm run build
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: change
